# Generated by Django 4.2.1 on 2023-05-10 22:06

from django.db import migrations, models
import theme_pixel.models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_details',
            field=models.ImageField(blank=True, null=True, upload_to=theme_pixel.models.filepath),
        ),
    ]
