# Generated by Django 4.2.1 on 2023-05-13 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theme_pixel', '0009_remove_rating_post_remove_rating_user_item_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rate',
        ),
        migrations.AddField(
            model_name='item',
            name='header',
            field=models.CharField(default='Header', max_length=100),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_pixel.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
