# Generated by Django 4.2.1 on 2023-05-13 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0010_remove_item_rate_item_header_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
