# Generated by Django 4.2.1 on 2023-05-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0011_item_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rate',
        ),
    ]
