# Generated by Django 4.2.1 on 2023-05-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0012_remove_item_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='header',
        ),
    ]
