# Generated by Django 4.2.1 on 2023-05-14 16:03

from django.db import migrations, models
import theme_pixel.models


class Migration(migrations.Migration):

    dependencies = [
        ('theme_pixel', '0013_remove_item_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=theme_pixel.models.filepath),
        ),
    ]
